version: '3.3'

# servicios a ejecutar
services:
    swapp-db:
        image: mysql:8.0.31
        container_name: swapp-db
        environment:
            - MYSQL_DATABASE=swapp
            - MYSQL_USER=cunigarro
            - MYSQL_PASSWORD=1113514597
            - MYSQL_ROOT_PASSWORD=1113514597
        ports:
            - '3306:3306'
        expose:
            - '3306'
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 20

    swapp-app:
        image: swapp:latest
        container_name: swapp-app
        build: .
        ports:
            - '8080:8080'
        expose:
            - '8080'
        depends_on:
            swapp-db:
                condition: service_healthy

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            - PMA_HOST=swapp-db
